### ISSUE TITLE
sGlobal.cppに定義された定数について

### ISSUE THREAD

**Issue by takjn** [wakayamarb/wrbb-v2lib-firm#10]
sGlobal.cppでは、INPUT_PULLUPがコメントアウトされて使えないようになっていますが、何か理由はありますでしょうか？

[CITRUSスケッチリファレンス](http://gadget.renesas.com/ja/reference/citrus/library_digitalio.html)のpinModeの項を見ますと、INPUTとOUTPUTの他に、INPUT_PULLUPとOUTPUT_OPENDRAINが指定できることになっています。
また、[SAKURAスケッチリファレンス](http://gadget.renesas.com/ja/reference/sakura/library_digitalio.html)では、さらにOUTPUT_HIGHも指定できることになっています。

**Comment by tarosay** [comment]
グローバル変数を確保した分RAMを消費していくので、最低限、今の6つぐらいデフォルトで指定しておけばいいかなと思った次第です。
　INPUT_PULLUPをコメントアウトしているのは「意識的に6つだけにしました」ということがわかるかなと思って、今回のような質問が来るかなと思ってです。
　mrb_define_global_const()したときに、CONSTなのでRAMを使わないのかなと思ったのですが、そうではないようです。
　rbファイルの方で、INPUT_PULLUP = 2 と定義してもらえばいいかなと思っているのですが、ここらへん、いかがでしょうか？

**Comment by takjn** [comment]
メモリの問題でしたか。了解です。
rbファイルの方で定義する件も了解です。

どこまでを標準の定数として定義して提供してあげるかは非常に悩ましいと思いますが、Aruino APIベースですのでArduino.hに定義されている定数で良く使われそうなものを優先的に定義するのが良いと思います。
