### ISSUE TITLE
mac環境でBREAKによる停止ができない

### ISSUE THREAD

**Issue by kimushu** [wakayamarb/wrbb-v2lib-firm#22]
※技術的な議論はFBよりもこちらが適切かと思いますので、issueを起こします。

mac環境(macOS High Sierra)ではUSB-CDCによるシリアルポートに対して、
BREAK信号の生成(ioctlのTIOCSBRK/TIOCCBRK)を行ってもUSB-CDCのClass request (23h)が生成されません(USBプロアナで確認)。

従って、mac環境では #16 で導入したプログラム中断機能が使用できません。Apple側ドライバでの早期改善は望み薄ですので、
なんらかの代替手段を検討するしかないと思っています。

**Comment by kimushu** [comment]
DTR(Data Terminal Ready)信号を用いる方式を提案しておきます。

- CITRUS側
  - Class Request 22hでDTR=OFFがリクエストされるとmrubyVMの停止要求フラグをセットする。
  - mrubyVMは停止要求フラグがセットされている場合、速やかにVMを終了する。(ここの実装は #16 のまま)
  - Rコマンド等でVMを開始する直前には、停止要求フラグをクリアする。(ここの実装は #16 のまま)
- PC(Rubic)側
  - DTR=OFF→DTR=ONを複数回(※)行い、Class Request 22h (with DTR=OFF)を生成させる。
    - (※)リクエストが通信異常によりNAKされた場合などを想定
  - VMの終了を待つ。(終了するまで上記リクエストを繰り返すのも可)

USB-CDCにおいてこの手の信号に意味をつける必要もないかもしれませんが、強いていえば
「PC(DTE側)がReadyではない」
→ 「PCはCITRUS(DCE側)に対しこれ以上の出力をして欲しくない」
→ 「PCはCITRUSのVMを止めたい」
というこじつけです。

なお、DTRやRTSは、端末ソフト(TeraTermやCoolTerm等)でポートを開くまではOFF、ポートを開いている間は原則ON (コマンドやGUI上でON/OFFできる)となります。
よって、この方式を使った場合、端末ソフトからRコマンドで手打ちして実行開始指示をしたのち、ポートを閉じるとVMが停止することになります。
(実行開始指示ののち、ポートを閉じた後も走らせ続けることはできなくなる)

**Comment by kimushu** [comment]
信号線としてはDTR/RTSくらいしか残っていないので、
残りの手段として思いつくのは「特殊なボーレート(300とか)への変更を要求すると停止要求と見なす」くらいでしょうか…

**Comment by tarosay** [comment]
GR-KURUMIは、DTRをLOWにしないとシリアル通信しなかったと思います。なので、GR-KURUMIと通信したいときは、わざわざTeraTermのマクロで、
connect '/C=5'
setdtr 0
というコマンドを動かします。
ここら辺を応用できないでしょうか？

**Comment by kimushu** [comment]
USB接続やDTR/RTSの持ちうる状態としては以下の表にまとめられるかと思います。

給電|USB接続|端末ソフト(TeraTermやCoolTermなど)|DTR|動作
---|---|---|---|---
無し|N/A|N/A|N/A|未給電。動作しない。
有り|未確立|N/A|N/A|自動起動で動作する(モバイルバッテリーや充電専用ケーブル等による給電)
有り|確立|接続前 / 切断後|OFF|★1
有り|確立|接続完了|ON|★2
有り|確立|接続完了後明示的にDTRをOFFに変更|OFF|★1

★1と★2の振る舞いをどうするか、を定義すればよいのかと。
私の元々の提案は★1=中断指示、★2=通常実行、というものです。USB繋いだままでも端末ソフト閉じると動作止まってしまいますが。

ちなみにDTRをOFFにしないと動かないGR-KURUMIさんは信号の意味からすると変ですね…。

**Comment by tarosay** [comment]
現在も、VS-Codeを閉じるとBREAKが発行されるようで、Ruby実行が止まりますね。
GR-KURUMIの場合、DTR ONがプログラム書き込みモードで、OFFがプログラム実行モードなんだと思います。
端末ソフトを閉じるとVMが強制終了してしまうのは、私的には容認できますが、都合が悪いようなアプリケーションを作っている人がいれば、困るかもしれませんね。
例えば、実行コマンドで、DTRブレイクを無効にする実行コマンドを用意するというのは、どうでしょうか？
R main.mrb ・・・DTR OFFで止まる
N main.mrb・・・DTR ON/OFFにかかわらず止まらない。
モバイルバッテリーでの給電の場合、N/Aなので止まってしまったりしないでしょうか？USB未確立の時は、Nコマンドで実行すればいいのかなと思いました。

**Comment by kimushu** [comment]
Rubicに関してはデバッグ終了時にBreak発行をしているので、実行が止まる挙動で正しいです。(実行させたままにするつもりも無かったので。

USBシリアルの場合DTRはその値が変化するときに専用のリクエストが飛んでくる、いわゆるエッジ検出のような形になるので、USB非接続の場合に誤認識することはないですね。
Nコマンドの追加は、要望があってからでもよいかと思います。

**Comment by kimushu** [comment]
後ほどプルリクを出します。
なお、"BREAK"による停止機能はしばらく残したままにしましょう。
