### ISSUE TITLE
定数追加やRubyらしく記述するためのSymbolでの引数などはどうでしょうか

### ISSUE THREAD

**Issue by paichi81** [wakayamarb/wrbb-v2lib-firm#3]
ファームウェア2.2を基準に提案します。
いまのところメソッド類がarduino寄りなので、そちらからの既存ユーザがmrubyでの開発をするにはとっつきやすいと思うのですが、Rubyらしくわかりやすいコードがかけるように、
- ON/HIGHを1, OFF/LOWを0にする等、よくある内容を組み込み定数にする
- pinMode等の引数にSymbolを指定できるようにする
- メソッド名をすべて小文字でaliasする
- useWiFi等、結果を1,0になるメソッドはbooleanで返すuse_wifi?のような末尾?でおわるメソッドでaliasする
- println をputsでalias
...以上いかがでしょうか？

```ruby:sample.rb
console = Serial.new(0)

pin_mode(5, INPUT) 
digital_write(5, :high)

10.times do
  [:on, :off].each do |sw|
    led sw
    delay 100
  end
end

if System.use_wifi? # => true
  console.puts "WA-MIKAN Enabled."
else #=> false
  console.puts "WA-MIKAN disable."
end
```

**Comment by tarosay** [comment]
返事が遅くて済みません。提案ありがとうございます。Rubyプログラマが書いて楽しくなるのが一番だと思います。
　ON/OFFなどを組み込み定数にする方法は調べてわかりました。ON/OFF, HIGH/LOW, INPUT/OUTPUTくらいでしょうか。あまり組み込み定数を増やすと、256KBしかないメモリを圧迫していくので、これ以上は、使う人の方にお願いしたいと思います。
　Symbolの処理をmruby実装のC側でどのように書けばいいのか、勉強不足でまだ、わかっていません。もし、ご存じであれば、教えてください。
　use_wifi?などの?付きのメソッドは、言われてみてそうですね必要だと思いました。ただ、alias設定できなくて、別メソッドで定義しないとダメなようです。これは、プログラムしてみます。
　useWiFi?以外に?付きのメソッドが欲しいメソッドってなにがありますでしょうか？
　メソッドをすべて小文字でaliasする件ですが、Ruby的にはすべて小文字というのが、いい感じなのでしょうか?
　私はRubyの決まり事をあまり理解していないので、いろいろと教えてください。
　ただ、mrubyの実装の方で、aliasaの方法が、今一つわからないのと、aliasするのと、別メソッドとして実装するのと、どちらがメモリの消費量が少ないか、検討する必要があります。
　mrubyの実装でメモリを使ってしまい、肝心のrubyプログラムを実行するメモリがほとんどないという状態だけは避けていと思っています。

　考え方が2つありまして、mruby実装を小さくして、Rubyのプログラム領域を広げて、いろいろRubyのプログラムを書いてもらうというのと、mruby実装にaliasなどいろいろあらかじめ入れておいて、それをRubyから呼び出す形でRubyプログラムを書いてもらう。
　このバランスをとるためには、本当はmrubyのbinのクロスコンパイルを各自に行ってもらえばいいのですが、現在はなかなかそこまでできる方がいらっしゃらない状況です。
　ながながとなりましたが、
定数を用意するのと、?のメソッドを用意することをやりたいと思います。
Symbolは、やり方を調べます。
aliasでメモリがどれくらい食われていくのか、調べてみます。
よろしくお願いします。

**Comment by paichi81** [comment]
返信ありがとうございます。
ユーザのプログラム側に8KBの制限があるので、ファームウェア側の拡張は(個々でも)必須なのかなと思いました。
小文字かどうかについては好き好きあると思いますが、ガイドライン的なものがあるかどうか探してみます。

とりあえずGR-CITRUS用については部品単位でオブジェクト指向的な考えができると、わかりやすいプログラムがかけそうなきがしたので、まだ実行してませんがサンプルとして下記のようなライブラリをつくってみています。
ただPureRubyで書いたライブラリをファームにどう積めばいいのかが分かりません;_;)
https://github.com/paichi81/81gr-citrus/blob/master/grcitrus_rubish.rb

上記を使って↓みたいに記述できると見通しがよくなりそうな気がしています。
```ruby:sample.rb
#
# ボタン2個で、モータ2つをそれぞれをまわすプログラム
#
class MyApplication
  def initialize
    @btns           = {}   #ボタン類管理
    @motors         = {} #モータ管理

    @btns[:left]    = Button.new(:pin_3)
    @btns[:right]   = Button.new(:pin_2)
    @motors[:left]  = TA7291P.new(:pin_5, :pin_6)
    @motors[:right] = TA7291P.new(:pin_7, :pin_8)
    @led_red_1      = Led.new(:pin_4)
    #@sensor         = SonicSensor_HCSR04.new(:pin_10, :pin_11)
  end

  def run
    loop do
      #右左用部品のロジック
      [:left, :right].each do |direction|
        if @btns[direction].clicked? #directionで指定した部品が押されたら
          @led_red1.on!
          @motors[direction].rotate! #回転するやで
        else
          @motors[direction].stop! #とめるやで
        end
      end

    end
  end
  
end

MyApplication.new.run
```

**Comment by paichi81** [comment]
メソッドやクラスの命名規則の情報ありました。なるほどなるほど。
http://qiita.com/takahashim/items/ccfd489c9b26f15b7193

**Comment by paichi81** [comment]
少しだけ検証してみました。あんまりガツガツとオブジェクト指向ぽくするのも現実的ではなさそうでした
http://qiita.com/paichi81@github/items/38c752862d5527762dee

**Comment by paichi81** [comment]
mrbgemでクラス定義することでPureRubyで思っていた機能がほぼほぼ実現できそうなことがわかりました。
http://qiita.com/paichi81@github/items/eaece4c38bc19b496073

使う部品に応じて気軽に切り替えたいところですが、いまはlibmruby作ってからファームウェアへの組み込みになるので少々手間はかかりますね...。

またコメント#2ででていたAlias登録ですが、mruby Coreのオブジェクト実装をみるかんじ、単純に別メソッドとしてInit内で定義されているようでした。いったん本issueはCloseしても大丈夫だと思いました。
お騒がせしました～
