### ISSUE TITLE
splitの挙動について

### ISSUE THREAD

**Issue by takjn** [wakayamarb/wrbb-v2lib-firm#6]
splitの挙動が、mirbで実行した場合と異なります。

host pc上のmrubyのmirbで以下のコードを実行すると

```
lines = "line1\r\nline2\r\nline3\r\nline4\r\nline5\r\n".split("\r\n")
lines.each { |line| puts line }
```

以下のように出力されます。
```
> lines = "line1\r\nline2\r\nline3\r\nline4\r\nline5\r\n".split("\r\n")
 => ["line1", "line2", "line3", "line4", "line5"]
> lines.each { |line| puts line }
line1
line2
line3
line4
line5
 => ["line1", "line2", "line3", "line4", "line5"]
```

一方、GR-CITRUS Ver. 2.2.6(2016/12/27)で以下のコードを実行すると、

```
#!mruby

@Usb = Serial.new(0,115200)

def puts(str)
    @Usb.println(str)
end

lines = "line1\r\nline2\r\nline3\r\nline4\r\nline5\r\n".split("\r\n")
lines.each { |line| puts line }
```

以下のように出力されます。

```
line1
line2
line3
line4
line5

line2
line3
line4
line5

line3
line4
line5

line4
line5

line5
```

なお、``lines.each { |line| puts line.chomp }``のように変更すると、mirbと同じ出力となります。

原因お分かりになりますでしょうか？

**Comment by tarosay** [comment]
返信が遅くてすみません。
mrubyのバージョンが違うのかなと思います。ただ、このファームでは、mruby-string-extのmrbgemを入れていないので、もともと.split は使えないと思うのですが、takjinさんの方でmruby-string-ext付でmakeしていませんでしょうか。そのときに使ったmrbgemとバージョンが変わったとか、ありませんでしょうか？

**Comment by takjn** [comment]
ご確認ありがとうございます。firmware_releaseフォルダ内に入っているcitrus_sketch.binで確認していますので、すくなくとも私のmakeの影響ではないと思います。[mrubyのStringクラスのドキュメント](http://mruby.org/docs/api/String.html)を見ると、splitはmrubyのStringクラスに入っているようです。実際に、firmware_releaseフォルダ内のlibmruby.aの中身を``nm libmruby.a | grep split``確認してみましたところ、string.oの中に``000018a0 t _mrb_str_split_m``がありました。

回避策（.chompをつける）があるので実害は無いと思いますが、GPSモジュールからのシリアル文字列をパースするときに若干ハマったので、もし原因がお分かりになれば、直しておきたいなあと思った次第です。

**Comment by tarosay** [comment]
最新のmrubyソースからlibmruby.aを作れば解決するのでしょうか。今使っているlibmruby.aは11/25にcloneしてmakeしたものだったような気がします。

**Comment by takjn** [comment]
原因は、sSerial.cppのmrb_serial_printlnのようです。

以下のコードを
```
	if(n > 0){
		serialc->println(RSTRING_PTR(text));
	}
	else{
		serialc->println();
	}
```

以下のように修正したところ、正しく表示されるようになりました。
```
	if(n > 0){
		serialc->write((const unsigned char *)RSTRING_PTR(text), RSTRING_LEN(text));
	}
	serialc->println();
```

[mruby の String から C 言語の文字列を取り出す正しい方法](http://qiita.com/tsahara@github/items/b2a442af95ac893e10a1)に解説がありましたが、RSTRING_PTRは、RSTRING_PTR と RSTRING_LENをセットで使う必要があるようです。
mruby本家のmirbのコードでも、RSTRING_PTR を使う際は RSTRING_LENとセットで使っていました。

**Comment by tarosay** [comment]
println(RSTRING_PTR(text))となっている箇所をwriteを使うように修正したものをコミットしました。

**Comment by takjn** [comment]
ありがとうございました！
2.28(2017/1/4)で解決されていることを確認しました。
